### ISSUE TITLE
node-red V0.20.5 Error: Cannot find module '/usr/local/lib/node_modules/node-red/red/red' (line:19)

### ISSUE THREAD

**Issue by riesenbaer1** [xTheRamon/node-red-contrib-mqtt-dynamictopic#3]
Hello,
after update to node-red V0.20.5  on a raspberry pi and a 
Red Hat Enterprise Linux Server release 6.10 
I got the errormessage 
Error: Cannot find module '/usr/local/lib/node_modules/node-red/red/red' (line:19)

node -v 
v8.11.3

komplett reinstallation of everything...... does not help.

Tanks for help.
riesenbaer1
please excuse my bad English

**Comment by tiagotfs** [comment]
Hi riesenbaer1,

Did you solve that? i've te same issue.

Regards.

**Comment by alexsahka** [comment]
The same problem 
Error: Cannot find module '/usr/local/lib/node_modules/node-red/red/red' (line:19)

**Comment by FredThx** [comment]
Same problem on node-red v1.0.1

**Comment by FredThx** [comment]
Solution : Change ../lib/mqttConnectionPool.js

Line 18 : comment the line
Line 115 : },5000);

**Comment by OI4-Hilscher** [comment]
We would love to use this node in a widely-used example for our customers, because it points to a problem we often see in the market. Unfortunately this node is not maintained anymore and does not work for newer Node-RED versions.
We have to consider to solve it in a different way or to reinvent a node with the same functionality.
Unfortunately a 2nd and 3rd node with the same functionality confuses Node-RED users more as it solve problems.

**Comment by xTheRamon** [comment]
@FredThx solved this issue in version 1.0.2, therefore I am closing this issue.
If there's any features you'd like to have added, please, be my guest and create a pull request. I do not have the time to maintain this node, but I will actively merge your pull requests :)
